spring.application.name=event-management

# Porta da aplicacao
server.port=8080

# Configuracao do H2
spring.datasource.url=jdbc:h2:file:./data/eventdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SpringDoc
springdoc.api-docs.path=/eventos-api-docs
springdoc.server.url=http://localhost:8080
springdoc.swagger-ui.url=/eventos-api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=MinhaChaveSuperSecretaComPeloMenos32Caracteres
jwt.expiration=86400000
