CREATE TABLE eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    data_hora TIMESTAMP NOT NULL,
    local VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    qtd_vagas INTEGER NOT NULL,
    categoria_id BIGINT NOT NULL,
    criador_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id),
    FOREIGN KEY (criador_id) REFERENCES users(id)
);
